name: A
on:
  push:
    branches:
      - "feature/personal-access-token"

permissions:
  pull-requests: write

jobs:
  output:
    name: Output 'A'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'A'
      - name: Create pull request
        uses: actions/github-script@v5
        continue-on-error: true
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Auto Pull Request by GitHub Actions`,
              head: "feature/personal-access-token",
              base: "develop"
            })
